import { NextRequest, NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
import {
  generateTimeSlots,
  isPeakSlot,
  needsLightingOption,
  normalizeHour,
  parsePeakSlots,
} from "@/lib/slots";
import { calculatePrice, generateBookingPin } from "@/lib/pricing";

export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    const {
      date,
      slotStart,
      firstName,
      lastName,
      roomNumber,
      racketCount,
      boughtBallsOnly,
      needsLighting,
    } = body;

    // Validation
    if (!date || !slotStart || !firstName || !lastName || !roomNumber) {
      return NextResponse.json(
        { error: "Missing required fields" },
        { status: 400 }
      );
    }

    if (racketCount < 0 || racketCount > 4) {
      return NextResponse.json(
        { error: "Invalid racket count (0-4)" },
        { status: 400 }
      );
    }

    // Guard: room number must be exactly 4 digits
    if (!/^\d{4}$/.test(String(roomNumber).trim())) {
      return NextResponse.json(
        { error: "Room number must be exactly 4 digits." },
        { status: 400 }
      );
    }

    // Guard: refuse bookings for slots already in the past
    const [slotHours, slotMinutes] = slotStart.split(":").map(Number);
    const slotDateTime = new Date(date + "T12:00:00");
    slotDateTime.setHours(slotHours, slotMinutes, 0, 0);
    if (slotDateTime < new Date()) {
      return NextResponse.json(
        { error: "Cannot book a time slot in the past." },
        { status: 400 }
      );
    }

    // Fetch settings for slot validation and server-side price calculation
    let settings: any = null;
    try {
      settings = await prisma.settings.findUnique({ where: { id: 1 } });
    } catch (error) {
      console.error("[BOOKINGS POST ERROR] Failed to fetch settings from DB, using defaults:", {
        message: error instanceof Error ? error.message : String(error),
      });
    }

    const defaultSettings = {
      id: 1,
      base_price: 100,
      racket_price_with_balls: 5,
      balls_only_price: 10,
      lighting_price: 20,
      peak_premium: 10,
      open_hour: "08:00",
      close_hour: "22:00",
      lighting_trigger_hour: "18:30",
      peak_slots: "[\"17:00\",\"18:30\",\"20:00\"]",
      slot_duration_minutes: 90,
      currency: "TND"
    };

    const activeSettings = settings || defaultSettings;

    // Guard: reject slots not generated by current settings
    const validSlots = generateTimeSlots(
      normalizeHour(activeSettings.open_hour),
      normalizeHour(activeSettings.close_hour),
      activeSettings.slot_duration_minutes || 90
    );
    if (!validSlots.includes(slotStart)) {
      return NextResponse.json(
        { error: "Invalid slot: outside current operating hours." },
        { status: 400 }
      );
    }

    const peakSlots = parsePeakSlots(activeSettings.peak_slots);
    const peak = isPeakSlot(slotStart, peakSlots);
    const lightingApplicable = needsLightingOption(slotStart, activeSettings.lighting_trigger_hour || "18:30");

    const breakdown = calculatePrice({
      basePrice: activeSettings.base_price,
      isPeak: peak,
      peakPremium: activeSettings.peak_premium,
      racketCount: Number(racketCount),
      racketPriceWithBalls: activeSettings.racket_price_with_balls,
      boughtBallsOnly: Boolean(boughtBallsOnly),
      ballsOnlyPrice: activeSettings.balls_only_price,
      needsLighting: lightingApplicable && Boolean(needsLighting),
      lightingPrice: activeSettings.lighting_price,
    });

    const bookingPin = generateBookingPin();

    // Create booking — @@unique([date, slot_start]) will throw P2002 if double-booked
    const booking = await prisma.booking.create({
      data: {
        booking_pin: bookingPin,
        type: "TOURIST_BOOKING",
        customer_first_name: firstName,
        customer_last_name: lastName,
        room_number: roomNumber,
        date,
        slot_start: slotStart,
        duration_minutes: activeSettings.slot_duration_minutes || 90,
        racket_count: Number(racketCount),
        bought_balls_only: Boolean(boughtBallsOnly) && Number(racketCount) === 0,
        needs_lighting: lightingApplicable && Boolean(needsLighting),
        total_price: breakdown.total,
        currency: activeSettings.currency || "TND",
        status: "PENDING_PAYMENT",
      },
    });

    return NextResponse.json({ booking }, { status: 201 });
  } catch (error: unknown) {
    // Prisma unique constraint violation — slot was taken concurrently
    if (
      error &&
      typeof error === "object" &&
      "code" in error &&
      (error as { code: string }).code === "P2002"
    ) {
      return NextResponse.json(
        { error: "SLOT_TAKEN", message: "This slot has just been booked by another guest." },
        { status: 409 }
      );
    }
    console.error("POST /api/bookings error:", error);
    return NextResponse.json({ error: "Server error" }, { status: 500 });
  }
}
